FROM nginx:1.13-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
COPY docker.png /usr/share/nginx/html/docker.png
ADD css /usr/share/nginx/html/css
ADD images /usr/share/nginx/html/images